### ISSUE TITLE
is fastestCar exercise answer pointfree?

### ISSUE THREAD

**Issue by radiofreejohn** [DrBoolean/mostly-adequate-guide#125]
I'm new to the pointfree concept, so I'm wondering if I'm misunderstanding, or reading too deeply into the definition of pointfree.

> It means functions that never mention the data upon which they operate.

```
var fastestCar = _.compose(append(' is the fastest'),
                           _.prop('name'),
                           _.last,
                           _.sortBy(_.prop('horsepower')))
```

In this example, the function is aware of the argument's structure (properties `name` and `horsepower`), is this still considered pointfree?

**Comment by tonyday** [comment]
Hi @radiofreejohn 
I am very much a newbie but here is my 2 pennies worth.
The function `fastestCar` is pointfree since it does not refer to its own argument(s) directly.
It is true that when we partially apply the `_.prop` functions we do refer to specific properties (which as you say implies a knowledge of their argument's structure).
However, I would suggest that it is no different to the the fact that `_.last` function is expecting an array or that the `append` function is expecting a string (both of which imply awareness of the "type" of the argument being passed).
A non-pointfree version might look something like this (assuming I got my parentheses correct):
````
var fastestCar = function (car_list) {
  return append(' is the fastest', _.prop('name', _.last(_.sortBy(_.prop('horsepower'), car_list))))
};
````
where in the function definition we refer directly to the named argument (`car_list`).
Not sure if this helps :-)

**Comment by radiofreejohn** [comment]
Definitely helps. I assumed I was being overly pedantic, but pointing out the assumption of array and string puts that into perspective, thanks!
